[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "microdb"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.4.1"
pyo3 = "0.12.3"

[lib]
name = "word_count"
crate-type = ["cdylib"]
